apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=asia-south1-docker.pkg.dev/argocd-777/web-app
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/nginx.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^.*
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/bitbucket-ssh
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: git@github.com:atulghodmare777/my-project.git
    targetRevision: main
    path: apps/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

