resources:
  - k8s/deployment.yaml
  - k8s/service.yaml
images:
  - name: asia-south1-docker.pkg.dev/argocd-777/web-app/my-image
    newTag: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: nginx-app
